---
version: 2
multicolumn: false
web-width: '820'
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/delta7SI/delta7SI.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/14026/articles/155729/master/folder/figures/delta7SI"
    url: "/users/14026/articles/155729/master/file/figures/delta7SI/delta7SI.html"
