---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/LinesAndTypes/LinesAndTypes.csv
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/14026/articles/155729/master/folder/figures/LinesAndTypes"
    treatFirstLineAsHeader: true
    url: "/users/14026/articles/155729/master/file/figures/LinesAndTypes/LinesAndTypes.csv"
