---
version: 2
multicolumn: false
web-width: 800
export-width: 
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Figure1-MethodsOverview-1/FigureProtocol.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/14026/articles/155729/master/folder/figures/Figure1-MethodsOverview-1"
    url: "/users/14026/articles/155729/master/file/figures/Figure1-MethodsOverview-1/FigureProtocol.svg"
