---
version: 2
multicolumn: 
web-width: '1500'
export-width: 
align: 
float: 
grid:
  rows: 1
  columns: 1
  grid_elements:
  - url: "/users/14026/articles/155729/master/file/figures/NetworkDiagram/NetworkDiagram.png"
    path: figures/NetworkDiagram/NetworkDiagram.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
