---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/doseRespSI/doseRespSI.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/14026/articles/155729/master/file/figures/doseRespSI/doseRespSI.svg"
    folder_url: "/users/14026/articles/155729/master/folder/figures/doseRespSI"
