---
version: 2
multicolumn: false
web-width: '1000'
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/statistics_histograms/statistics_histograms.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/14026/articles/155729/master/file/figures/statistics_histograms/statistics_histograms.svg"
    folder_url: "/users/14026/articles/155729/master/folder/figures/statistics_histograms"
