---
version: 2
multicolumn: false
web-width: '1000'
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/picroSI/picroPlots.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/14026/articles/155729/master/folder/figures/picroSI"
    url: "/users/14026/articles/155729/master/file/figures/picroSI/picroPlots.html"
export-width: '500'
