---
version: 2
multicolumn: false
web-width: '1300'
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/matIntegNorm/Screenshot-2018-2-2 Results figure.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/14026/articles/155729/master/folder/figures/matIntegNorm"
    url: "/users/14026/articles/155729/master/file/figures/matIntegNorm/Screenshot-2018-2-2%20Results%20figure.png"
export-width: '500'
export-filename: Screenshot-2018-2-2 Results figure.png
