---
version: 2
multicolumn: false
web-width: '1300'
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/matIntegNorm/resultsFigureLight.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/14026/articles/155729/master/folder/figures/matIntegNorm"
    url: "/users/14026/articles/155729/master/file/figures/matIntegNorm/resultsFigureLight.html"
export-width: '400'
export-filename: ScreenshotResults figure.png
