---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/EPGtoPFL/EPGtoPFL.gif
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/14026/articles/155729/master/file/figures/EPGtoPFL/EPGtoPFL.gif"
