---
version: 2
multicolumn: false
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/mat/mat.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/14026/articles/155729/master/folder/figures/mat"
    url: "/users/14026/articles/155729/master/file/figures/mat/mat.svg"
