---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/matDistance/matDistance.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/14026/articles/155729/master/file/figures/matDistance/matDistance.html"
